package parser

var divisions = []Division{
	// 直辖市
	{Province: "北京市", City: "北京市", District: "东城区"},
	{Province: "北京市", City: "北京市", District: "西城区"},
	{Province: "北京市", City: "北京市", District: "朝阳区"},
	{Province: "北京市", City: "北京市", District: "丰台区"},
	{Province: "北京市", City: "北京市", District: "石景山区"},
	{Province: "北京市", City: "北京市", District: "海淀区"},
	{Province: "北京市", City: "北京市", District: "门头沟区"},
	{Province: "北京市", City: "北京市", District: "房山区"},
	{Province: "北京市", City: "北京市", District: "通州区"},
	{Province: "北京市", City: "北京市", District: "顺义区"},
	{Province: "北京市", City: "北京市", District: "昌平区"},
	{Province: "北京市", City: "北京市", District: "大兴区"},
	{Province: "北京市", City: "北京市", District: "怀柔区"},
	{Province: "北京市", City: "北京市", District: "平谷区"},
	{Province: "北京市", City: "北京市", District: "密云区"},
	{Province: "北京市", City: "北京市", District: "延庆区"},
	
	{Province: "上海市", City: "上海市", District: "黄浦区"},
	{Province: "上海市", City: "上海市", District: "徐汇区"},
	{Province: "上海市", City: "上海市", District: "长宁区"},
	{Province: "上海市", City: "上海市", District: "静安区"},
	{Province: "上海市", City: "上海市", District: "普陀区"},
	{Province: "上海市", City: "上海市", District: "虹口区"},
	{Province: "上海市", City: "上海市", District: "杨浦区"},
	{Province: "上海市", City: "上海市", District: "闵行区"},
	{Province: "上海市", City: "上海市", District: "宝山区"},
	{Province: "上海市", City: "上海市", District: "嘉定区"},
	{Province: "上海市", City: "上海市", District: "浦东新区"},
	{Province: "上海市", City: "上海市", District: "金山区"},
	{Province: "上海市", City: "上海市", District: "松江区"},
	{Province: "上海市", City: "上海市", District: "青浦区"},
	{Province: "上海市", City: "上海市", District: "奉贤区"},
	{Province: "上海市", City: "上海市", District: "崇明区"},
	
	{Province: "天津市", City: "天津市", District: "和平区"},
	{Province: "天津市", City: "天津市", District: "河东区"},
	{Province: "天津市", City: "天津市", District: "河西区"},
	{Province: "天津市", City: "天津市", District: "南开区"},
	{Province: "天津市", City: "天津市", District: "河北区"},
	{Province: "天津市", City: "天津市", District: "红桥区"},
	{Province: "天津市", City: "天津市", District: "东丽区"},
	{Province: "天津市", City: "天津市", District: "西青区"},
	{Province: "天津市", City: "天津市", District: "津南区"},
	{Province: "天津市", City: "天津市", District: "北辰区"},
	{Province: "天津市", City: "天津市", District: "武清区"},
	{Province: "天津市", City: "天津市", District: "宝坻区"},
	{Province: "天津市", City: "天津市", District: "滨海新区"},
	{Province: "天津市", City: "天津市", District: "宁河区"},
	{Province: "天津市", City: "天津市", District: "静海区"},
	{Province: "天津市", City: "天津市", District: "蓟州区"},
	
	{Province: "重庆市", City: "重庆市", District: "万州区"},
	{Province: "重庆市", City: "重庆市", District: "涪陵区"},
	{Province: "重庆市", City: "重庆市", District: "渝中区"},
	{Province: "重庆市", City: "重庆市", District: "大渡口区"},
	{Province: "重庆市", City: "重庆市", District: "江北区"},
	{Province: "重庆市", City: "重庆市", District: "沙坪坝区"},
	{Province: "重庆市", City: "重庆市", District: "九龙坡区"},
	{Province: "重庆市", City: "重庆市", District: "南岸区"},
	{Province: "重庆市", City: "重庆市", District: "北碚区"},
	{Province: "重庆市", City: "重庆市", District: "綦江区"},
	{Province: "重庆市", City: "重庆市", District: "大足区"},
	{Province: "重庆市", City: "重庆市", District: "渝北区"},
	{Province: "重庆市", City: "重庆市", District: "巴南区"},
	{Province: "重庆市", City: "重庆市", District: "黔江区"},
	{Province: "重庆市", City: "重庆市", District: "长寿区"},
	{Province: "重庆市", City: "重庆市", District: "江津区"},
	{Province: "重庆市", City: "重庆市", District: "合川区"},
	{Province: "重庆市", City: "重庆市", District: "永川区"},
	{Province: "重庆市", City: "重庆市", District: "南川区"},
	{Province: "重庆市", City: "重庆市", District: "璧山区"},
	{Province: "重庆市", City: "重庆市", District: "铜梁区"},
	{Province: "重庆市", City: "重庆市", District: "潼南区"},
	{Province: "重庆市", City: "重庆市", District: "荣昌区"},
	{Province: "重庆市", City: "重庆市", District: "开州区"},
	{Province: "重庆市", City: "重庆市", District: "梁平区"},
	{Province: "重庆市", City: "重庆市", District: "武隆区"},
	
	// 副省级城市及省会城市
	{Province: "黑龙江省", City: "哈尔滨市", District: "道里区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "南岗区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "道外区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "平房区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "松北区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "香坊区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "呼兰区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "阿城区"},
	{Province: "黑龙江省", City: "哈尔滨市", District: "双城区"},
	
	{Province: "吉林省", City: "长春市", District: "南关区"},
	{Province: "吉林省", City: "长春市", District: "宽城区"},
	{Province: "吉林省", City: "长春市", District: "朝阳区"},
	{Province: "吉林省", City: "长春市", District: "二道区"},
	{Province: "吉林省", City: "长春市", District: "绿园区"},
	{Province: "吉林省", City: "长春市", District: "双阳区"},
	{Province: "吉林省", City: "长春市", District: "九台区"},
	
	{Province: "辽宁省", City: "沈阳市", District: "和平区"},
	{Province: "辽宁省", City: "沈阳市", District: "沈河区"},
	{Province: "辽宁省", City: "沈阳市", District: "大东区"},
	{Province: "辽宁省", City: "沈阳市", District: "皇姑区"},
	{Province: "辽宁省", City: "沈阳市", District: "铁西区"},
	{Province: "辽宁省", City: "沈阳市", District: "苏家屯区"},
	{Province: "辽宁省", City: "沈阳市", District: "浑南区"},
	{Province: "辽宁省", City: "沈阳市", District: "沈北新区"},
	{Province: "辽宁省", City: "沈阳市", District: "于洪区"},
	{Province: "辽宁省", City: "沈阳市", District: "辽中区"},
	
	{Province: "辽宁省", City: "大连市", District: "中山区"},
	{Province: "辽宁省", City: "大连市", District: "西岗区"},
	{Province: "辽宁省", City: "大连市", District: "沙河口区"},
	{Province: "辽宁省", City: "大连市", District: "甘井子区"},
	{Province: "辽宁省", City: "大连市", District: "旅顺口区"},
	{Province: "辽宁省", City: "大连市", District: "金州区"},
	{Province: "辽宁省", City: "大连市", District: "普兰店区"},
	
	{Province: "山东省", City: "济南市", District: "历下区"},
	{Province: "山东省", City: "济南市", District: "市中区"},
	{Province: "山东省", City: "济南市", District: "槐荫区"},
	{Province: "山东省", City: "济南市", District: "天桥区"},
	{Province: "山东省", City: "济南市", District: "历城区"},
	{Province: "山东省", City: "济南市", District: "长清区"},
	{Province: "山东省", City: "济南市", District: "章丘区"},
	{Province: "山东省", City: "济南市", District: "济阳区"},
	{Province: "山东省", City: "济南市", District: "莱芜区"},
	{Province: "山东省", City: "济南市", District: "钢城区"},
	
	{Province: "山东省", City: "青岛市", District: "市南区"},
	{Province: "山东省", City: "青岛市", District: "市北区"},
	{Province: "山东省", City: "青岛市", District: "黄岛区"},
	{Province: "山东省", City: "青岛市", District: "崂山区"},
	{Province: "山东省", City: "青岛市", District: "李沧区"},
	{Province: "山东省", City: "青岛市", District: "城阳区"},
	{Province: "山东省", City: "青岛市", District: "即墨区"},
	
	{Province: "江苏省", City: "南京市", District: "玄武区"},
	{Province: "江苏省", City: "南京市", District: "秦淮区"},
	{Province: "江苏省", City: "南京市", District: "建邺区"},
	{Province: "江苏省", City: "南京市", District: "鼓楼区"},
	{Province: "江苏省", City: "南京市", District: "浦口区"},
	{Province: "江苏省", City: "南京市", District: "栖霞区"},
	{Province: "江苏省", City: "南京市", District: "雨花台区"},
	{Province: "江苏省", City: "南京市", District: "江宁区"},
	{Province: "江苏省", City: "南京市", District: "六合区"},
	{Province: "江苏省", City: "南京市", District: "溧水区"},
	{Province: "江苏省", City: "南京市", District: "高淳区"},
	
	{Province: "浙江省", City: "杭州市", District: "上城区"},
	{Province: "浙江省", City: "杭州市", District: "下城区"},
	{Province: "浙江省", City: "杭州市", District: "江干区"},
	{Province: "浙江省", City: "杭州市", District: "拱墅区"},
	{Province: "浙江省", City: "杭州市", District: "西湖区"},
	{Province: "浙江省", City: "杭州市", District: "滨江区"},
	{Province: "浙江省", City: "杭州市", District: "萧山区"},
	{Province: "浙江省", City: "杭州市", District: "余杭区"},
	{Province: "浙江省", City: "杭州市", District: "富阳区"},
	{Province: "浙江省", City: "杭州市", District: "临安区"},
	
	{Province: "浙江省", City: "宁波市", District: "海曙区"},
	{Province: "浙江省", City: "宁波市", District: "江北区"},
	{Province: "浙江省", City: "宁波市", District: "北仑区"},
	{Province: "浙江省", City: "宁波市", District: "镇海区"},
	{Province: "浙江省", City: "宁波市", District: "鄞州区"},
	
	{Province: "福建省", City: "福州市", District: "鼓楼区"},
	{Province: "福建省", City: "福州市", District: "台江区"},
	{Province: "福建省", City: "福州市", District: "仓山区"},
	{Province: "福建省", City: "福州市", District: "马尾区"},
	{Province: "福建省", City: "福州市", District: "晋安区"},
	{Province: "福建省", City: "福州市", District: "长乐区"},
	
	{Province: "福建省", City: "厦门市", District: "思明区"},
	{Province: "福建省", City: "厦门市", District: "海沧区"},
	{Province: "福建省", City: "厦门市", District: "湖里区"},
	{Province: "福建省", City: "厦门市", District: "集美区"},
	{Province: "福建省", City: "厦门市", District: "同安区"},
	{Province: "福建省", City: "厦门市", District: "翔安区"},
	
	{Province: "广东省", City: "广州市", District: "荔湾区"},
	{Province: "广东省", City: "广州市", District: "越秀区"},
	{Province: "广东省", City: "广州市", District: "海珠区"},
	{Province: "广东省", City: "广州市", District: "天河区"},
	{Province: "广东省", City: "广州市", District: "白云区"},
	{Province: "广东省", City: "广州市", District: "黄埔区"},
	{Province: "广东省", City: "广州市", District: "番禺区"},
	{Province: "广东省", City: "广州市", District: "花都区"},
	{Province: "广东省", City: "广州市", District: "南沙区"},
	{Province: "广东省", City: "广州市", District: "从化区"},
	{Province: "广东省", City: "广州市", District: "增城区"},
	
	{Province: "广东省", City: "深圳市", District: "罗湖区"},
	{Province: "广东省", City: "深圳市", District: "福田区"},
	{Province: "广东省", City: "深圳市", District: "南山区"},
	{Province: "广东省", City: "深圳市", District: "宝安区"},
	{Province: "广东省", City: "深圳市", District: "龙岗区"},
	{Province: "广东省", City: "深圳市", District: "盐田区"},
	{Province: "广东省", City: "深圳市", District: "龙华区"},
	{Province: "广东省", City: "深圳市", District: "坪山区"},
	{Province: "广东省", City: "深圳市", District: "光明区"},
	
	{Province: "湖北省", City: "武汉市", District: "江岸区"},
	{Province: "湖北省", City: "武汉市", District: "江汉区"},
	{Province: "湖北省", City: "武汉市", District: "硚口区"},
	{Province: "湖北省", City: "武汉市", District: "汉阳区"},
	{Province: "湖北省", City: "武汉市", District: "武昌区"},
	{Province: "湖北省", City: "武汉市", District: "青山区"},
	{Province: "湖北省", City: "武汉市", District: "洪山区"},
	{Province: "湖北省", City: "武汉市", District: "东西湖区"},
	{Province: "湖北省", City: "武汉市", District: "汉南区"},
	{Province: "湖北省", City: "武汉市", District: "蔡甸区"},
	{Province: "湖北省", City: "武汉市", District: "江夏区"},
	{Province: "湖北省", City: "武汉市", District: "黄陂区"},
	{Province: "湖北省", City: "武汉市", District: "新洲区"},
	
	{Province: "四川省", City: "成都市", District: "锦江区"},
	{Province: "四川省", City: "成都市", District: "青羊区"},
	{Province: "四川省", City: "成都市", District: "金牛区"},
	{Province: "四川省", City: "成都市", District: "武侯区"},
	{Province: "四川省", City: "成都市", District: "成华区"},
	{Province: "四川省", City: "成都市", District: "龙泉驿区"},
	{Province: "四川省", City: "成都市", District: "青白江区"},
	{Province: "四川省", City: "成都市", District: "新都区"},
	{Province: "四川省", City: "成都市", District: "温江区"},
	{Province: "四川省", City: "成都市", District: "双流区"},
	{Province: "四川省", City: "成都市", District: "郫都区"},
	
	{Province: "陕西省", City: "西安市", District: "新城区"},
	{Province: "陕西省", City: "西安市", District: "碑林区"},
	{Province: "陕西省", City: "西安市", District: "莲湖区"},
	{Province: "陕西省", City: "西安市", District: "灞桥区"},
	{Province: "陕西省", City: "西安市", District: "未央区"},
	{Province: "陕西省", City: "西安市", District: "雁塔区"},
	{Province: "陕西省", City: "西安市", District: "阎良区"},
	{Province: "陕西省", City: "西安市", District: "临潼区"},
	{Province: "陕西省", City: "西安市", District: "长安区"},
	{Province: "陕西省", City: "西安市", District: "高陵区"},
	{Province: "陕西省", City: "西安市", District: "鄠邑区"},
	
	// 其他省会城市
	{Province: "河北省", City: "石家庄市", District: "长安区"},
	{Province: "河北省", City: "石家庄市", District: "桥西区"},
	{Province: "河北省", City: "石家庄市", District: "新华区"},
	{Province: "河北省", City: "石家庄市", District: "井陉矿区"},
	{Province: "河北省", City: "石家庄市", District: "裕华区"},
	{Province: "河北省", City: "石家庄市", District: "藁城区"},
	{Province: "河北省", City: "石家庄市", District: "鹿泉区"},
	{Province: "河北省", City: "石家庄市", District: "栾城区"},
	
	{Province: "山西省", City: "太原市", District: "小店区"},
	{Province: "山西省", City: "太原市", District: "迎泽区"},
	{Province: "山西省", City: "太原市", District: "杏花岭区"},
	{Province: "山西省", City: "太原市", District: "尖草坪区"},
	{Province: "山西省", City: "太原市", District: "万柏林区"},
	{Province: "山西省", City: "太原市", District: "晋源区"},
	
	{Province: "内蒙古自治区", City: "呼和浩特市", District: "新城区"},
	{Province: "内蒙古自治区", City: "呼和浩特市", District: "回民区"},
	{Province: "内蒙古自治区", City: "呼和浩特市", District: "玉泉区"},
	{Province: "内蒙古自治区", City: "呼和浩特市", District: "赛罕区"},
	
	{Province: "安徽省", City: "合肥市", District: "瑶海区"},
	{Province: "安徽省", City: "合肥市", District: "庐阳区"},
	{Province: "安徽省", City: "合肥市", District: "蜀山区"},
	{Province: "安徽省", City: "合肥市", District: "包河区"},
	
	{Province: "江西省", City: "南昌市", District: "东湖区"},
	{Province: "江西省", City: "南昌市", District: "西湖区"},
	{Province: "江西省", City: "南昌市", District: "青云谱区"},
	{Province: "江西省", City: "南昌市", District: "青山湖区"},
	{Province: "江西省", City: "南昌市", District: "新建区"},
	
	{Province: "河南省", City: "郑州市", District: "中原区"},
	{Province: "河南省", City: "郑州市", District: "二七区"},
	{Province: "河南省", City: "郑州市", District: "管城回族区"},
	{Province: "河南省", City: "郑州市", District: "金水区"},
	{Province: "河南省", City: "郑州市", District: "上街区"},
	{Province: "河南省", City: "郑州市", District: "惠济区"},
	{Province: "河南省", City: "郑州市", District: "中牟县"},
	
	{Province: "湖南省", City: "长沙市", District: "芙蓉区"},
	{Province: "湖南省", City: "长沙市", District: "天心区"},
	{Province: "湖南省", City: "长沙市", District: "岳麓区"},
	{Province: "湖南省", City: "长沙市", District: "开福区"},
	{Province: "湖南省", City: "长沙市", District: "雨花区"},
	{Province: "湖南省", City: "长沙市", District: "望城区"},
	
	{Province: "广西壮族自治区", City: "南宁市", District: "兴宁区"},
	{Province: "广西壮族自治区", City: "南宁市", District: "青秀区"},
	{Province: "广西壮族自治区", City: "南宁市", District: "江南区"},
	{Province: "广西壮族自治区", City: "南宁市", District: "西乡塘区"},
	{Province: "广西壮族自治区", City: "南宁市", District: "良庆区"},
	{Province: "广西壮族自治区", City: "南宁市", District: "邕宁区"},
	{Province: "广西壮族自治区", City: "南宁市", District: "武鸣区"},
	
	{Province: "海南省", City: "海口市", District: "秀英区"},
	{Province: "海南省", City: "海口市", District: "龙华区"},
	{Province: "海南省", City: "海口市", District: "琼山区"},
	{Province: "海南省", City: "海口市", District: "美兰区"},
	
	{Province: "贵州省", City: "贵阳市", District: "南明区"},
	{Province: "贵州省", City: "贵阳市", District: "云岩区"},
	{Province: "贵州省", City: "贵阳市", District: "花溪区"},
	{Province: "贵州省", City: "贵阳市", District: "乌当区"},
	{Province: "贵州省", City: "贵阳市", District: "白云区"},
	{Province: "贵州省", City: "贵阳市", District: "观山湖区"},
	
	{Province: "云南省", City: "昆明市", District: "五华区"},
	{Province: "云南省", City: "昆明市", District: "盘龙区"},
	{Province: "云南省", City: "昆明市", District: "官渡区"},
	{Province: "云南省", City: "昆明市", District: "西山区"},
	{Province: "云南省", City: "昆明市", District: "东川区"},
	{Province: "云南省", City: "昆明市", District: "呈贡区"},
	{Province: "云南省", City: "昆明市", District: "晋宁区"},
	
	{Province: "西藏自治区", City: "拉萨市", District: "城关区"},
	{Province: "西藏自治区", City: "拉萨市", District: "堆龙德庆区"},
	{Province: "西藏自治区", City: "拉萨市", District: "达孜区"},
	
	{Province: "甘肃省", City: "兰州市", District: "城关区"},
	{Province: "甘肃省", City: "兰州市", District: "七里河区"},
	{Province: "甘肃省", City: "兰州市", District: "西固区"},
	{Province: "甘肃省", City: "兰州市", District: "安宁区"},
	{Province: "甘肃省", City: "兰州市", District: "红古区"},
	
	{Province: "青海省", City: "西宁市", District: "城东区"},
	{Province: "青海省", City: "西宁市", District: "城中区"},
	{Province: "青海省", City: "西宁市", District: "城西区"},
	{Province: "青海省", City: "西宁市", District: "城北区"},
	{Province: "青海省", City: "西宁市", District: "湟中区"},
	
	{Province: "宁夏回族自治区", City: "银川市", District: "兴庆区"},
	{Province: "宁夏回族自治区", City: "银川市", District: "西夏区"},
	{Province: "宁夏回族自治区", City: "银川市", District: "金凤区"},
	
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "天山区"},
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "沙依巴克区"},
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "新市区"},
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "水磨沟区"},
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "头屯河区"},
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "达坂城区"},
	{Province: "新疆维吾尔自治区", City: "乌鲁木齐市", District: "米东区"},
}
