export enum ErrorCode {
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_BASE_SALARY = 'INVALID_BASE_SALARY',
  INVALID_PERFORMANCE_COEFFICIENT = 'INVALID_PERFORMANCE_COEFFICIENT',
  INVALID_SOCIAL_INSURANCE_RATE = 'INVALID_SOCIAL_INSURANCE_RATE',
  INVALID_HOUSING_FUND_RATE = 'INVALID_HOUSING_FUND_RATE',
  INVALID_TAX_THRESHOLD = 'INVALID_TAX_THRESHOLD',
  INVALID_OVERTIME_HOURS = 'INVALID_OVERTIME_HOURS',
  INVALID_LEAVE_DEDUCTION = 'INVALID_LEAVE_DEDUCTION',
  INVALID_YEAR_END_BONUS = 'INVALID_YEAR_END_BONUS',
  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  INVALID_MONTH_FORMAT = 'INVALID_MONTH_FORMAT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export interface ApiError {
  code: ErrorCode;
  message: string;
}

export function createApiError(code: ErrorCode, message: string): ApiError {
  return { code, message };
}
