package mockgen

import (
	"bytes"
	"fmt"
	"strings"
)

type Generator struct {
	conf *GeneratorConfig
}

func NewGenerator() *Generator {
	return NewGeneratorWithConfig(NewGeneratorConfig())
}

func NewGeneratorWithConfig(conf *GeneratorConfig) *Generator {
	if conf == nil {
		conf = NewGeneratorConfig()
	}
	return &Generator{conf: conf}
}

func (g *Generator) Generate(info *InterfaceInfo) (string, error) {
	pkg := info.Package
	if g.conf.Package != "" {
		pkg = g.conf.Package
	}
	mockName := "Mock" + info.Name

	var buf bytes.Buffer

	buf.WriteString("// Code generated by gomock-generator. DO NOT EDIT.\n")
	buf.WriteString("// This file is a mock implementation of " + info.Name + ".\n\n")
	buf.WriteString("package " + pkg + "\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"sync\"\n")
	buf.WriteString(")\n\n")

	g.writeMockStruct(&buf, mockName, info.Methods)
	g.writeNewMock(&buf, mockName, info.Methods)
	g.writeBaseMethods(&buf, mockName)

	for _, m := range info.Methods {
		g.writeMethodConfig(&buf, mockName, m)
	}

	g.writeCallRecord(&buf)

	return buf.String(), nil
}

func (g *Generator) writeMockStruct(buf *bytes.Buffer, mockName string, methods []Method) {
	buf.WriteString("type " + mockName + " struct {\n")
	buf.WriteString("\tmu    sync.Mutex\n")
	buf.WriteString("\tcalls []CallRecord\n")
	for _, m := range methods {
		buf.WriteString("\t" + m.Name + "Config *" + m.Name + "MethodConfig\n")
	}
	buf.WriteString("}\n\n")
}

func (g *Generator) writeNewMock(buf *bytes.Buffer, mockName string, methods []Method) {
	buf.WriteString("func New" + mockName + "() *" + mockName + " {\n")
	buf.WriteString("\tm := &" + mockName + "{}\n")
	for _, m := range methods {
		buf.WriteString("\tm." + m.Name + "Config = &" + m.Name + "MethodConfig{}\n")
	}
	buf.WriteString("\treturn m\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeBaseMethods(buf *bytes.Buffer, mockName string) {
	buf.WriteString("func (m *" + mockName + ") recordCall(methodName string, params []interface{}, results []interface{}) {\n")
	buf.WriteString("\tm.mu.Lock()\n")
	buf.WriteString("\tdefer m.mu.Unlock()\n")
	buf.WriteString("\tm.calls = append(m.calls, CallRecord{\n")
	buf.WriteString("\t\tMethodName: methodName,\n")
	buf.WriteString("\t\tParams:     params,\n")
	buf.WriteString("\t\tResults:    results,\n")
	buf.WriteString("\t})\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (m *" + mockName + ") Calls() []CallRecord {\n")
	buf.WriteString("\tm.mu.Lock()\n")
	buf.WriteString("\tdefer m.mu.Unlock()\n")
	buf.WriteString("\tcopied := make([]CallRecord, len(m.calls))\n")
	buf.WriteString("\tcopy(copied, m.calls)\n")
	buf.WriteString("\treturn copied\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (m *" + mockName + ") Reset() {\n")
	buf.WriteString("\tm.mu.Lock()\n")
	buf.WriteString("\tdefer m.mu.Unlock()\n")
	buf.WriteString("\tm.calls = nil\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeMethodConfig(buf *bytes.Buffer, mockName string, m Method) {
	paramsDeclForFuncType := g.joinParamDeclsForFuncType(m.Params, m.IsVariadic)
	hasResults := len(m.Results) > 0
	returnsStruct := m.Name + "Returns"
	needsStruct := len(m.Results) > 1

	if needsStruct {
		buf.WriteString("type " + returnsStruct + " struct {\n")
		for i, r := range m.Results {
			buf.WriteString(fmt.Sprintf("\tR%d %s\n", i, r.Type))
		}
		buf.WriteString("}\n\n")
	}

	buf.WriteString("type " + m.Name + "MethodConfig struct {\n")
	buf.WriteString("\tmu       sync.Mutex\n")
	if hasResults {
		if needsStruct {
			buf.WriteString("\tdefaults " + returnsStruct + "\n")
		} else {
			buf.WriteString("\tdefaults " + m.Results[0].Type + "\n")
		}
	}
	buf.WriteString("\texpects  []" + m.Name + "Expectation\n")
	buf.WriteString("}\n\n")

	buf.WriteString("type " + m.Name + "Expectation struct {\n")
	if paramsDeclForFuncType != "" {
		buf.WriteString("\tmatcher    func(" + paramsDeclForFuncType + ") bool\n")
	} else {
		buf.WriteString("\tmatcher    func() bool\n")
	}
	if hasResults {
		if needsStruct {
			buf.WriteString("\treturns    " + returnsStruct + "\n")
		} else {
			buf.WriteString("\treturns    " + m.Results[0].Type + "\n")
		}
	}
	buf.WriteString("\tminCalls   int\n")
	buf.WriteString("\tmaxCalls   int\n")
	buf.WriteString("\tactualCalls int\n")
	buf.WriteString("}\n\n")

	g.writeOnMethod(buf, mockName, m)
	g.writeSetDefault(buf, mockName, m)
	g.writeSetReturn(buf, mockName, m)
	g.writeExpectationMethods(buf, m)
	if hasResults {
		g.writeFindMatch(buf, mockName, m)
	}
	g.writeMockMethod(buf, mockName, m)
}

func (g *Generator) writeOnMethod(buf *bytes.Buffer, mockName string, m Method) {
	buf.WriteString("func (m *" + mockName + ") On" + m.Name + "() *" + m.Name + "Expectation {\n")
	buf.WriteString("\tm." + m.Name + "Config.mu.Lock()\n")
	buf.WriteString("\tdefer m." + m.Name + "Config.mu.Unlock()\n")
	buf.WriteString("\tvar exp " + m.Name + "Expectation\n")
	if len(m.Results) > 0 {
		buf.WriteString("\texp.returns = m." + m.Name + "Config.defaults\n")
	}
	buf.WriteString("\texp.maxCalls = -1\n")
	buf.WriteString("\tm." + m.Name + "Config.expects = append(m." + m.Name + "Config.expects, exp)\n")
	buf.WriteString("\treturn &m." + m.Name + "Config.expects[len(m." + m.Name + "Config.expects)-1]\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeSetDefault(buf *bytes.Buffer, mockName string, m Method) {
	if len(m.Results) == 0 {
		return
	}

	resultsDecl := g.joinResultDecls(m.Results)
	resultsNames := g.joinResultNames(m.Results)
	needsStruct := len(m.Results) > 1

	buf.WriteString("func (m *" + mockName + ") Set" + m.Name + "Default(" + resultsDecl + ") *" + mockName + " {\n")
	buf.WriteString("\tm." + m.Name + "Config.mu.Lock()\n")
	buf.WriteString("\tdefer m." + m.Name + "Config.mu.Unlock()\n")
	if needsStruct {
		buf.WriteString("\tm." + m.Name + "Config.defaults = " + m.Name + "Returns{" + resultsNames + "}\n")
	} else {
		buf.WriteString("\tm." + m.Name + "Config.defaults = " + resultsNames + "\n")
	}
	buf.WriteString("\treturn m\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeSetReturn(buf *bytes.Buffer, mockName string, m Method) {
	if len(m.Results) == 0 {
		return
	}

	resultsDecl := g.joinResultDecls(m.Results)
	resultsNames := g.joinResultNames(m.Results)
	needsStruct := len(m.Results) > 1

	buf.WriteString("func (m *" + mockName + ") Set" + m.Name + "Return(" + resultsDecl + ") *" + mockName + " {\n")
	buf.WriteString("\tm.On" + m.Name + "().SetReturn(" + resultsNames + ")\n")
	buf.WriteString("\treturn m\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (e *" + m.Name + "Expectation) SetReturn(" + resultsDecl + ") *" + m.Name + "Expectation {\n")
	if needsStruct {
		buf.WriteString("\te.returns = " + m.Name + "Returns{" + resultsNames + "}\n")
	} else {
		buf.WriteString("\te.returns = " + resultsNames + "\n")
	}
	buf.WriteString("\treturn e\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeExpectationMethods(buf *bytes.Buffer, m Method) {
	buf.WriteString("func (e *" + m.Name + "Expectation) Times(n int) *" + m.Name + "Expectation {\n")
	buf.WriteString("\te.minCalls = n\n")
	buf.WriteString("\te.maxCalls = n\n")
	buf.WriteString("\treturn e\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (e *" + m.Name + "Expectation) MinTimes(n int) *" + m.Name + "Expectation {\n")
	buf.WriteString("\te.minCalls = n\n")
	buf.WriteString("\treturn e\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (e *" + m.Name + "Expectation) MaxTimes(n int) *" + m.Name + "Expectation {\n")
	buf.WriteString("\te.maxCalls = n\n")
	buf.WriteString("\treturn e\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeFindMatch(buf *bytes.Buffer, mockName string, m Method) {
	paramsDecl := g.joinParamDeclsForFuncType(m.Params, m.IsVariadic)
	paramsNames := g.joinParamNamesForFuncType(m.Params)
	needsStruct := len(m.Results) > 1

	returnsType := ""
	if needsStruct {
		returnsType = m.Name + "Returns"
	} else {
		returnsType = m.Results[0].Type
	}

	buf.WriteString("func (m *" + mockName + ") find" + m.Name + "Match(" + paramsDecl + ") (" + returnsType + ", bool) {\n")
	buf.WriteString("\tm." + m.Name + "Config.mu.Lock()\n")
	buf.WriteString("\tdefer m." + m.Name + "Config.mu.Unlock()\n")
	buf.WriteString("\tfor i := range m." + m.Name + "Config.expects {\n")
	buf.WriteString("\t\texp := &m." + m.Name + "Config.expects[i]\n")
	buf.WriteString("\t\tif exp.maxCalls >= 0 && exp.actualCalls >= exp.maxCalls {\n")
	buf.WriteString("\t\t\tcontinue\n")
	buf.WriteString("\t\t}\n")
	if paramsNames != "" {
		buf.WriteString("\t\tif exp.matcher == nil || exp.matcher(" + paramsNames + ") {\n")
	} else {
		buf.WriteString("\t\tif exp.matcher == nil || exp.matcher() {\n")
	}
	buf.WriteString("\t\t\texp.actualCalls++\n")
	buf.WriteString("\t\t\treturn exp.returns, true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn m." + m.Name + "Config.defaults, false\n")
	buf.WriteString("}\n\n")
}

func (g *Generator) writeMockMethod(buf *bytes.Buffer, mockName string, m Method) {
	paramsDeclForMock := g.joinParamDecls(m.Params, m.IsVariadic)
	paramsNamesForCall := g.joinParamNamesForFuncType(m.Params)
	paramsNamesForRecord := g.joinParamNamesForFuncType(m.Params)
	resultsStr := g.joinResultTypes(m.Results)
	hasResults := len(m.Results) > 0
	needsStruct := len(m.Results) > 1

	buf.WriteString("func (m *" + mockName + ") " + m.Name + "(" + paramsDeclForMock + ") " + resultsStr + " {\n")
	if hasResults {
		if paramsNamesForCall != "" {
			buf.WriteString("\tresults, ok := m.find" + m.Name + "Match(" + paramsNamesForCall + ")\n")
		} else {
			buf.WriteString("\tresults, ok := m.find" + m.Name + "Match()\n")
		}
		buf.WriteString("\tif !ok {\n")
		buf.WriteString("\t\tpanic(fmt.Sprintf(\"" + mockName + "." + m.Name + ": no matching expectation or default set\"))\n")
		buf.WriteString("\t}\n")

		recordParams := "nil"
		if paramsNamesForRecord != "" {
			recordParams = "[]interface{}{" + paramsNamesForRecord + "}"
		}

		if needsStruct {
			buf.WriteString("\tresultsIface := []interface{}{")
			for i := range m.Results {
				if i > 0 {
					buf.WriteString(", ")
				}
				buf.WriteString(fmt.Sprintf("results.R%d", i))
			}
			buf.WriteString("}\n")
			buf.WriteString("\tm.recordCall(\"" + m.Name + "\", " + recordParams + ", resultsIface)\n")
			buf.WriteString("\treturn ")
			for i := range m.Results {
				if i > 0 {
					buf.WriteString(", ")
				}
				buf.WriteString(fmt.Sprintf("results.R%d", i))
			}
			buf.WriteString("\n")
		} else {
			buf.WriteString("\tm.recordCall(\"" + m.Name + "\", " + recordParams + ", []interface{}{results})\n")
			buf.WriteString("\treturn results\n")
		}
	} else {
		recordParams := "nil"
		if paramsNamesForRecord != "" {
			recordParams = "[]interface{}{" + paramsNamesForRecord + "}"
		}
		buf.WriteString("\tm.recordCall(\"" + m.Name + "\", " + recordParams + ", nil)\n")
	}
	buf.WriteString("}\n\n")
}

func (g *Generator) writeCallRecord(buf *bytes.Buffer) {
	buf.WriteString("type CallRecord struct {\n")
	buf.WriteString("\tMethodName string\n")
	buf.WriteString("\tParams     []interface{}\n")
	buf.WriteString("\tResults    []interface{}\n")
	buf.WriteString("}\n")
}

func (g *Generator) joinParamDecls(params []Parameter, isVariadic bool) string {
	var parts []string
	for i, p := range params {
		typeStr := p.Type
		if isVariadic && i == len(params)-1 {
			parts = append(parts, p.Name+" "+typeStr)
		} else {
			parts = append(parts, p.Name+" "+typeStr)
		}
	}
	return strings.Join(parts, ", ")
}

func (g *Generator) joinParamDeclsForFuncType(params []Parameter, isVariadic bool) string {
	var parts []string
	for i, p := range params {
		typeStr := p.Type
		if isVariadic && i == len(params)-1 {
			typeStr = strings.Replace(typeStr, "...", "[]", 1)
		}
		parts = append(parts, p.Name+" "+typeStr)
	}
	return strings.Join(parts, ", ")
}

func (g *Generator) joinParamNames(params []Parameter, isVariadic bool) string {
	var names []string
	for i, p := range params {
		if isVariadic && i == len(params)-1 {
			names = append(names, p.Name+"...")
		} else {
			names = append(names, p.Name)
		}
	}
	return strings.Join(names, ", ")
}

func (g *Generator) joinParamNamesForFuncType(params []Parameter) string {
	var names []string
	for _, p := range params {
		names = append(names, p.Name)
	}
	return strings.Join(names, ", ")
}

func (g *Generator) joinParamNamesForRecord(params []Parameter, isVariadic bool) string {
	var names []string
	for i, p := range params {
		if isVariadic && i == len(params)-1 {
			names = append(names, p.Name)
		} else {
			names = append(names, p.Name)
		}
	}
	return strings.Join(names, ", ")
}

func (g *Generator) joinResultDecls(results []Parameter) string {
	var parts []string
	for _, r := range results {
		parts = append(parts, r.Name+" "+r.Type)
	}
	return strings.Join(parts, ", ")
}

func (g *Generator) joinResultNames(results []Parameter) string {
	var names []string
	for _, r := range results {
		names = append(names, r.Name)
	}
	return strings.Join(names, ", ")
}

func (g *Generator) joinResultTypes(results []Parameter) string {
	if len(results) == 0 {
		return ""
	}
	var parts []string
	for _, r := range results {
		parts = append(parts, r.Type)
	}
	if len(results) == 1 {
		return parts[0]
	}
	return "(" + strings.Join(parts, ", ") + ")"
}
