from enum import IntEnum


class ErrorCode(IntEnum):
    SUCCESS = 0
    OUTBOUND_NOT_FOUND = 1001
    OUTBOUND_ALREADY_COMPLETED = 1002
    RETURN_QUANTITY_EXCEEDED = 1003
    RETURN_NOT_FOUND = 1004
    RETURN_STATUS_INVALID = 1005
    RETURN_EXPIRED = 1006
    ITEM_NOT_IN_OUTBOUND = 1007
    INSPECTION_ALREADY_DONE = 1008
    STOCKIN_DEADLINE_PASSED = 1009
    DEFECTIVE_NOT_FOUND = 1010
    INVALID_INSPECTION_RESULT = 1011
    INSUFFICIENT_STOCK = 1012
    QUALITY_ALERT_THRESHOLD_NOT_SET = 1013
    INVALID_DATE_RANGE = 1014
    INTERNAL_ERROR = 9999


class ReturnConstants:
    RETURN_VALIDITY_DAYS = 7
    STOCKIN_DEADLINE_DAYS = 3
    DEFECTIVE_PRICE_RATE = 0.8
    DEFAULT_QUALITY_ALERT_THRESHOLD = 0.1

    VALID_DISPOSAL_REASONS = {
        "quality_issue",
        "size_mismatch",
        "dislike",
        "wrong_item",
        "other",
    }
