-- Generated by go-db-dumper at 2026-05-05 13:27:39
-- Source file: test_special.csv

BEGIN;
INSERT INTO special_table (id, "select", "order", "name with space") VALUES (1, 'value1', 1, 'O''Conner');
INSERT INTO special_table (id, "select", "order", "name with space") VALUES (2, 'value2', 2, 'Smith');
COMMIT;

