-- Generated by go-db-dumper at 2026-05-05 13:27:17
-- Source file: test_empty.csv

-- Note: CSV file contains only headers, no data rows.
-- Table name would be: test_empty
-- Columns: id, name, email
