-- Generated by go-db-dumper at 2026-05-05 13:26:43
-- Source file: test_users.csv

BEGIN;
INSERT INTO users (id, name, email, age, is_active) VALUES (1, 'John Doe', 'john@example.com', 30, 'true');
INSERT INTO users (id, name, email, age, is_active) VALUES (2, 'Jane Smith', 'jane@example.com', 25, 'false');
INSERT INTO users (id, name, email, age, is_active) VALUES (3, 'Bob, Jr.', 'bob@example.com', 35, 'true');
INSERT INTO users (id, name, email, age, is_active) VALUES (4, 'Alice Johnson', 'alice@example.com', 28, NULL);
INSERT INTO users (id, name, email, age, is_active) VALUES (5, 'Charlie Brown', 'charlie@example.com', NULL, 'true');
COMMIT;

