from enum import Enum


class ErrorCode(str, Enum):
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    SAME_OPERATOR_FOR_INBOUND_OUTBOUND = "SAME_OPERATOR_FOR_INBOUND_OUTBOUND"
    ITEM_MISMATCH = "ITEM_MISMATCH"
    TIMEOUT_OCCURRED = "TIMEOUT_OCCURRED"
    CROSS_DAY_VIOLATION = "CROSS_DAY_VIOLATION"
    BATCH_NOT_READY = "BATCH_NOT_READY"
    INVALID_OPERATOR = "INVALID_OPERATOR"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    OUTBOUND_ORDER_NOT_FOUND = "OUTBOUND_ORDER_NOT_FOUND"
    EXCEPTION_PLAN_NOT_FOUND = "EXCEPTION_PLAN_NOT_FOUND"


class ErrorMessage:
    ORDER_NOT_FOUND = "越库单不存在"
    INVALID_STATUS_TRANSITION = "无效的状态转换"
    SAME_OPERATOR_FOR_INBOUND_OUTBOUND = "入库和出库必须由不同操作员完成"
    ITEM_MISMATCH = "商品不一致"
    TIMEOUT_OCCURRED = "越库单已超时"
    CROSS_DAY_VIOLATION = "入库和出库必须在同一天完成"
    BATCH_NOT_READY = "批量越库单未全部完成入库"
    INVALID_OPERATOR = "无效的操作员ID"
    DUPLICATE_ORDER = "越库单号已存在"
    OUTBOUND_ORDER_NOT_FOUND = "出库单号不存在"
    EXCEPTION_PLAN_NOT_FOUND = "异常处理预案不存在"


ERROR_MESSAGES: dict[str, str] = {
    ErrorCode.ORDER_NOT_FOUND: ErrorMessage.ORDER_NOT_FOUND,
    ErrorCode.INVALID_STATUS_TRANSITION: ErrorMessage.INVALID_STATUS_TRANSITION,
    ErrorCode.SAME_OPERATOR_FOR_INBOUND_OUTBOUND: ErrorMessage.SAME_OPERATOR_FOR_INBOUND_OUTBOUND,
    ErrorCode.ITEM_MISMATCH: ErrorMessage.ITEM_MISMATCH,
    ErrorCode.TIMEOUT_OCCURRED: ErrorMessage.TIMEOUT_OCCURRED,
    ErrorCode.CROSS_DAY_VIOLATION: ErrorMessage.CROSS_DAY_VIOLATION,
    ErrorCode.BATCH_NOT_READY: ErrorMessage.BATCH_NOT_READY,
    ErrorCode.INVALID_OPERATOR: ErrorMessage.INVALID_OPERATOR,
    ErrorCode.DUPLICATE_ORDER: ErrorMessage.DUPLICATE_ORDER,
    ErrorCode.OUTBOUND_ORDER_NOT_FOUND: ErrorMessage.OUTBOUND_ORDER_NOT_FOUND,
    ErrorCode.EXCEPTION_PLAN_NOT_FOUND: ErrorMessage.EXCEPTION_PLAN_NOT_FOUND,
}
