[package]
name = "ticket_server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ticket_server"
path = "src/main.rs"

[dependencies]
ticket_core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
