[package]
name = "contract_client"
version.workspace = true
edition.workspace = true

[dependencies]
contract_core = { path = "../core" }
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
