server.port=8512

spring.application.name=load-balancer

# Load Balancer 配置
loadbalancer.default-strategy=ROUND_ROBIN
loadbalancer.warmup-seconds=5
loadbalancer.health-check.interval=10000
loadbalancer.health-check.timeout=3000
loadbalancer.health-check.path=/health
