package enum

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"math"
	"sort"
	"strconv"
	"strings"
)

type EnumConstant struct {
	Name    string
	Value   int64
	Comment string
}

type EnumDefinition struct {
	TypeName  string
	Constants []EnumConstant
	UseInt64  bool
}

func Parse(r io.Reader, filename string) ([]EnumDefinition, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, r, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("解析Go文件失败: %w", err)
	}

	var enums []EnumDefinition

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		enumName := extractEnumMarker(genDecl.Doc)
		if enumName == "" {
			continue
		}

		constants, useInt64, err := extractConstants(genDecl)
		if err != nil {
			return nil, fmt.Errorf("提取常量失败: %w", err)
		}

		if len(constants) == 0 {
			continue
		}

		enums = append(enums, EnumDefinition{
			TypeName:  enumName,
			Constants: constants,
			UseInt64:  useInt64,
		})
	}

	return enums, nil
}

func extractEnumMarker(doc *ast.CommentGroup) string {
	if doc == nil {
		return ""
	}

	for _, comment := range doc.List {
		text := strings.TrimSpace(comment.Text)
		if strings.HasPrefix(text, "//go:enum") {
			parts := strings.Fields(text)
			if len(parts) >= 2 {
				return parts[1]
			}
		}
	}

	return ""
}

func extractConstants(genDecl *ast.GenDecl) ([]EnumConstant, bool, error) {
	var constants []EnumConstant
	var useInt64 bool
	var lastValue int64
	firstIota := true

	for _, spec := range genDecl.Specs {
		valueSpec, ok := spec.(*ast.ValueSpec)
		if !ok || len(valueSpec.Names) == 0 {
			continue
		}

		name := valueSpec.Names[0].Name
		if !token.IsIdentifier(name) || name == "_" {
			continue
		}

		var value int64
		var err error

		if len(valueSpec.Values) > 0 {
			value, err = evaluateExpr(valueSpec.Values[0])
			if err != nil {
				return nil, false, fmt.Errorf("计算表达式失败: %w", err)
			}
			lastValue = value
		} else {
			if firstIota {
				value = 0
				firstIota = false
			} else {
				value = lastValue + 1
			}
			lastValue = value
		}

		if value > math.MaxInt32 || value < math.MinInt32 {
			useInt64 = true
		}

		comment := extractConstantComment(valueSpec.Doc)

		constants = append(constants, EnumConstant{
			Name:    name,
			Value:   value,
			Comment: comment,
		})
	}

	return constants, useInt64, nil
}

func evaluateExpr(expr ast.Expr) (int64, error) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind == token.INT {
			return strconv.ParseInt(e.Value, 0, 64)
		}
		return 0, fmt.Errorf("不支持的常量类型: %v", e.Kind)
	case *ast.UnaryExpr:
		if e.Op == token.SUB {
			val, err := evaluateExpr(e.X)
			if err != nil {
				return 0, err
			}
			return -val, nil
		}
		return 0, fmt.Errorf("不支持的一元运算符: %v", e.Op)
	case *ast.Ident:
		if e.Name == "iota" {
			return 0, nil
		}
		return 0, fmt.Errorf("不支持的标识符: %s", e.Name)
	default:
		return 0, fmt.Errorf("不支持的表达式类型: %T", e)
	}
}

func extractConstantComment(doc *ast.CommentGroup) string {
	if doc == nil {
		return ""
	}

	var lines []string
	for _, comment := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if text != "" {
			lines = append(lines, text)
		}
	}

	return strings.Join(lines, " ")
}

func Generate(pkgName string, enums []EnumDefinition) ([]byte, error) {
	if len(enums) == 0 {
		return nil, nil
	}

	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by go-enum-generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"encoding/json\"\n")
	fmt.Fprintf(&buf, "\t\"fmt\"\n")
	fmt.Fprintf(&buf, "\t\"strings\"\n")
	fmt.Fprintf(&buf, ")\n\n")

	for _, enum := range enums {
		generateEnum(&buf, enum)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("格式化代码失败: %w\n原始代码:\n%s", err, buf.String())
	}

	return formatted, nil
}

func generateEnum(buf *bytes.Buffer, enum EnumDefinition) {
	intType := "int32"
	if enum.UseInt64 {
		intType = "int64"
	}

	fmt.Fprintf(buf, "type %s %s\n\n", enum.TypeName, intType)

	fmt.Fprintf(buf, "const (\n")
	for _, c := range enum.Constants {
		fmt.Fprintf(buf, "\t%s %s = %d\n", c.Name, enum.TypeName, c.Value)
	}
	fmt.Fprintf(buf, ")\n\n")

	generateStringMethod(buf, enum)
	generateMarshalJSON(buf, enum)
	generateUnmarshalJSON(buf, enum)
}

func generateStringMethod(buf *bytes.Buffer, enum EnumDefinition) {
	valueToName := make(map[int64]string)
	for _, c := range enum.Constants {
		if _, exists := valueToName[c.Value]; !exists {
			valueToName[c.Value] = c.Name
		}
	}

	values := make([]int64, 0, len(valueToName))
	for v := range valueToName {
		values = append(values, v)
	}
	sort.Slice(values, func(i, j int) bool { return values[i] < values[j] })

	fmt.Fprintf(buf, "func (e %s) String() string {\n", enum.TypeName)
	fmt.Fprintf(buf, "\tswitch e {\n")
	for _, v := range values {
		name := valueToName[v]
		var comment string
		for _, c := range enum.Constants {
			if c.Value == v && c.Name == name {
				comment = c.Comment
				break
			}
		}
		if comment != "" {
			fmt.Fprintf(buf, "\tcase %s: // %s\n", name, comment)
		} else {
			fmt.Fprintf(buf, "\tcase %s:\n", name)
		}
		fmt.Fprintf(buf, "\t\treturn \"%s\"\n", name)
	}
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Sprintf(\"%s(%%d)\", e)\n", enum.TypeName)
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
}

func generateMarshalJSON(buf *bytes.Buffer, enum EnumDefinition) {
	fmt.Fprintf(buf, "func (e %s) MarshalJSON() ([]byte, error) {\n", enum.TypeName)
	fmt.Fprintf(buf, "\treturn json.Marshal(e.String())\n")
	fmt.Fprintf(buf, "}\n\n")
}

func generateUnmarshalJSON(buf *bytes.Buffer, enum EnumDefinition) {
	nameToValue := make(map[string]int64)
	var validNames []string
	for _, c := range enum.Constants {
		nameToValue[strings.ToUpper(c.Name)] = c.Value
		validNames = append(validNames, c.Name)
	}

	fmt.Fprintf(buf, "func (e *%s) UnmarshalJSON(data []byte) error {\n", enum.TypeName)
	fmt.Fprintf(buf, "\tvar s string\n")
	fmt.Fprintf(buf, "\tif err := json.Unmarshal(data, &s); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch strings.ToUpper(s) {\n")

	for name, value := range nameToValue {
		var constName string
		for _, c := range enum.Constants {
			if c.Value == value {
				constName = c.Name
				break
			}
		}
		fmt.Fprintf(buf, "\tcase \"%s\":\n", name)
		fmt.Fprintf(buf, "\t\t*e = %s\n", constName)
	}

	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Errorf(\"invalid %s value: %%s, valid values are: %%v\", s, []string{", enum.TypeName)
	for i, name := range validNames {
		if i > 0 {
			fmt.Fprintf(buf, ", ")
		}
		fmt.Fprintf(buf, "\"%s\"", name)
	}
	fmt.Fprintf(buf, "})\n")

	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
}
