from enum import Enum


class ErrorCode(str, Enum):
    SUCCESS = "SUCCESS"

    SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND"
    SUPPLIER_ALREADY_EXISTS = "SUPPLIER_ALREADY_EXISTS"
    SUPPLIER_NOT_APPROVED = "SUPPLIER_NOT_APPROVED"
    SUPPLIER_SUSPENDED = "SUPPLIER_SUSPENDED"

    PURCHASE_NOT_FOUND = "PURCHASE_NOT_FOUND"
    PURCHASE_NOT_PUBLISHED = "PURCHASE_NOT_PUBLISHED"
    PURCHASE_ALREADY_CLOSED = "PURCHASE_ALREADY_CLOSED"
    PURCHASE_DEADLINE_PASSED = "PURCHASE_DEADLINE_PASSED"

    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    QUOTE_ALREADY_SUBMITTED = "QUOTE_ALREADY_SUBMITTED"
    QUOTE_CANNOT_MODIFY = "QUOTE_CANNOT_MODIFY"

    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_ALREADY_CONFIRMED = "ORDER_ALREADY_CONFIRMED"

    INVALID_INPUT = "INVALID_INPUT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


ERROR_MESSAGES: dict[ErrorCode, str] = {
    ErrorCode.SUCCESS: "操作成功",
    ErrorCode.SUPPLIER_NOT_FOUND: "供应商不存在",
    ErrorCode.SUPPLIER_ALREADY_EXISTS: "供应商已存在",
    ErrorCode.SUPPLIER_NOT_APPROVED: "供应商未通过审核",
    ErrorCode.SUPPLIER_SUSPENDED: "供应商已被暂停资格",
    ErrorCode.PURCHASE_NOT_FOUND: "采购需求不存在",
    ErrorCode.PURCHASE_NOT_PUBLISHED: "采购需求未发布",
    ErrorCode.PURCHASE_ALREADY_CLOSED: "采购需求已关闭",
    ErrorCode.PURCHASE_DEADLINE_PASSED: "报价截止时间已过",
    ErrorCode.QUOTE_NOT_FOUND: "报价不存在",
    ErrorCode.QUOTE_EXPIRED: "报价已过期",
    ErrorCode.QUOTE_ALREADY_SUBMITTED: "报价已提交",
    ErrorCode.QUOTE_CANNOT_MODIFY: "报价无法修改",
    ErrorCode.ORDER_NOT_FOUND: "采购订单不存在",
    ErrorCode.ORDER_ALREADY_CONFIRMED: "订单已确认",
    ErrorCode.INVALID_INPUT: "输入参数无效",
    ErrorCode.PERMISSION_DENIED: "权限不足",
    ErrorCode.INTERNAL_ERROR: "内部服务器错误",
}
