MAX_PACKAGE_WEIGHT_KG = 30.0
MAX_PACKAGE_VOLUME_M3 = 0.1
VOLUME_UTILIZATION_RATE = 0.8

ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
PACKAGE_NOT_FOUND = "PACKAGE_NOT_FOUND"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
BOX_TYPE_NOT_FOUND = "BOX_TYPE_NOT_FOUND"
TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"

WEIGHT_EXCEEDS_LIMIT = "WEIGHT_EXCEEDS_LIMIT"
VOLUME_EXCEEDS_LIMIT = "VOLUME_EXCEEDS_LIMIT"
HEAVY_ITEM_MUST_BE_ALONE = "HEAVY_ITEM_MUST_BE_ALONE"
FRAGILE_MUST_BE_ON_BOTTOM = "FRAGILE_MUST_BE_ON_BOTTOM"
VOLUME_UTILIZATION_EXCEEDED = "VOLUME_UTILIZATION_EXCEEDED"

PACKAGE_ALREADY_SHIPPED = "PACKAGE_ALREADY_SHIPPED"
ORDER_ALREADY_SHIPPED = "ORDER_ALREADY_SHIPPED"

INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"

DUPLICATE_ORDER_ID = "DUPLICATE_ORDER_ID"
DUPLICATE_BOX_TYPE = "DUPLICATE_BOX_TYPE"

INVALID_OPERATION = "INVALID_OPERATION"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
