package codegen

import (
	"bytes"
	"go/format"
	"text/template"
)

const codeTemplate = `// Code generated by errcode-gen. DO NOT EDIT.
// This file was generated from error code definition YAML.

package {{.PackageName}}

import (
	"errors"
	"fmt"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"net/http"
)

type ErrorCategory string

const (
{{range .Categories}}	{{.}} ErrorCategory = "{{.}}"
{{end}}
)

type ErrorCode int

const (
{{range .Errors}}{{if .Deprecated}}	// Deprecated: use alternative error code
{{end}}	{{.Name}} ErrorCode = {{.Code}}
{{end}}
)

type Error struct {
	Code      ErrorCode
	Message   string
	HTTPStatus int
	GRPCCode  codes.Code
	Category  ErrorCategory
	Details   map[string]interface{}
	cause     error
}

func (e *Error) Error() string {
	return e.Message
}

func (e *Error) Unwrap() error {
	return e.cause
}

func (e *Error) Is(target error) bool {
	var t *Error
	if !errors.As(target, &t) {
		return false
	}
	return e.Code == t.Code
}

func (e *Error) Wrap(err error) *Error {
	if err == nil {
		return nil
	}
	return &Error{
		Code:      e.Code,
		Message:   e.Message,
		HTTPStatus: e.HTTPStatus,
		GRPCCode:  e.GRPCCode,
		Category:  e.Category,
		Details:   e.Details,
		cause:     err,
	}
}

func (e *Error) UnwrapChain() []error {
	chain := []error{}
	current := e
	for current != nil {
		chain = append(chain, current)
		if current.cause == nil {
			break
		}
		var ok bool
		current, ok = current.cause.(*Error)
		if !ok {
			chain = append(chain, current.cause)
			break
		}
	}
	return chain
}

func (e *Error) WithDetails(details map[string]interface{}) *Error {
	newErr := *e
	newDetails := make(map[string]interface{})
	for k, v := range e.Details {
		newDetails[k] = v
	}
	for k, v := range details {
		newDetails[k] = v
	}
	newErr.Details = newDetails
	return &newErr
}

func (e *Error) WithMessage(format string, args ...interface{}) *Error {
	newErr := *e
	newErr.Message = fmt.Sprintf(format, args...)
	return &newErr
}

func (e *Error) ToGRPCStatus() *status.Status {
	return status.New(e.GRPCCode, e.Message)
}

func (e *Error) ToHTTPStatus() int {
	return e.HTTPStatus
}

{{range .Errors}}
func New{{.Name}}(args ...interface{}) *Error {
	msg := {{printf "%q" .Message}}
	if len(args) > 0 {
		msg = fmt.Sprintf(msg, args...)
	}
	return &Error{
		Code:       {{.Name}},
		Message:    msg,
		HTTPStatus: {{.HTTPStatus}},
		GRPCCode:   codes.{{.GRPCCode}},
		Category:   {{.Category}},
		Details:    make(map[string]interface{}),
	}
}
{{end}}

func FromCode(code ErrorCode) *Error {
	switch code {
{{range .Errors}}	case {{.Name}}:
		return New{{.Name}}()
{{end}}
	default:
		return NewINTERNAL_ERROR()
	}
}
`

type templateData struct {
	PackageName string
	Categories  []string
	Errors      []ValidatedError
}

func Generate(errors []ValidatedError, packageName string) (string, error) {
	categorySet := make(map[string]bool)
	for _, e := range errors {
		categorySet[e.Category] = true
	}
	var categories []string
	for c := range categorySet {
		categories = append(categories, c)
	}

	tmpl, err := template.New("code").Parse(codeTemplate)
	if err != nil {
		return "", err
	}

	data := templateData{
		PackageName: packageName,
		Categories:  categories,
		Errors:      errors,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), err
	}

	return string(formatted), nil
}
