[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
food_procure_core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
clap = { version = "4.0", features = ["derive", "env"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking", "rustls-tls"] }
