package server

import (
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"

	"go-db-dumper/proto"
)

type SQLGenerator struct {
	config *proto.ConverterConfig
}

func NewSQLGenerator(config *proto.ConverterConfig) *SQLGenerator {
	if config == nil {
		config = proto.DefaultConverterConfig()
	}
	return &SQLGenerator{
		config: config,
	}
}

func (g *SQLGenerator) Generate(csvData *CSVData, tableName string, sourceFile string, writer io.Writer) (int, error) {
	sqlCount := 0

	err := g.writeHeader(sourceFile, writer)
	if err != nil {
		return 0, err
	}

	if len(csvData.Rows) == 0 {
		return g.writeEmptyDataComment(csvData, tableName, writer)
	}

	columnNames := g.processColumnNames(csvData.Headers)

	for i := 0; i < len(csvData.Rows); i += g.config.BatchSize {
		end := i + g.config.BatchSize
		if end > len(csvData.Rows) {
			end = len(csvData.Rows)
		}

		batchRows := csvData.Rows[i:end]
		err := g.writeTransaction(tableName, columnNames, batchRows, writer)
		if err != nil {
			return sqlCount, err
		}

		sqlCount += len(batchRows)
	}

	return sqlCount, nil
}

func (g *SQLGenerator) writeHeader(sourceFile string, writer io.Writer) error {
	header := fmt.Sprintf("-- Generated by go-db-dumper at %s\n", time.Now().Format("2006-01-02 15:04:05"))
	header += fmt.Sprintf("-- Source file: %s\n", sourceFile)
	header += "\n"

	_, err := writer.Write([]byte(header))
	return err
}

func (g *SQLGenerator) writeEmptyDataComment(csvData *CSVData, tableName string, writer io.Writer) (int, error) {
	comment := "-- Note: CSV file contains only headers, no data rows.\n"
	comment += fmt.Sprintf("-- Table name would be: %s\n", tableName)
	comment += fmt.Sprintf("-- Columns: %s\n", strings.Join(csvData.Headers, ", "))

	_, err := writer.Write([]byte(comment))
	return 0, err
}

func (g *SQLGenerator) processColumnNames(headers []string) []string {
	processed := make([]string, len(headers))
	for i, header := range headers {
		processed[i] = g.quoteColumnNameIfNeeded(header)
	}
	return processed
}

func (g *SQLGenerator) quoteColumnNameIfNeeded(name string) string {
	upperName := strings.ToUpper(name)

	if g.config.SQLKeywords[upperName] {
		return fmt.Sprintf(`"%s"`, name)
	}

	for _, c := range name {
		if !isValidIdentifierChar(c) {
			return fmt.Sprintf(`"%s"`, name)
		}
	}

	return name
}

func isValidIdentifierChar(c rune) bool {
	return (c >= 'a' && c <= 'z') ||
		(c >= 'A' && c <= 'Z') ||
		(c >= '0' && c <= '9') ||
		c == '_'
}

func (g *SQLGenerator) writeTransaction(tableName string, columnNames []string, rows [][]string, writer io.Writer) error {
	if len(rows) == 0 {
		return nil
	}

	_, err := writer.Write([]byte("BEGIN;\n"))
	if err != nil {
		return err
	}

	for _, row := range rows {
		sql := g.generateInsertStatement(tableName, columnNames, row)
		_, err := writer.Write([]byte(sql + "\n"))
		if err != nil {
			return err
		}
	}

	_, err = writer.Write([]byte("COMMIT;\n\n"))
	return err
}

func (g *SQLGenerator) generateInsertStatement(tableName string, columnNames []string, row []string) string {
	quotedTableName := g.quoteColumnNameIfNeeded(tableName)
	columnsStr := strings.Join(columnNames, ", ")

	var values []string
	for i, val := range row {
		if i < len(columnNames) {
			values = append(values, g.formatValue(val))
		}
	}

	for i := len(row); i < len(columnNames); i++ {
		values = append(values, "NULL")
	}

	valuesStr := strings.Join(values, ", ")

	return fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s);", quotedTableName, columnsStr, valuesStr)
}

func (g *SQLGenerator) formatValue(value string) string {
	if g.config.HandleNull {
		for _, nullStr := range g.config.NullStrings {
			if value == nullStr {
				return "NULL"
			}
		}
	}

	if g.isNumeric(value) {
		return value
	}

	if g.config.EscapeQuotes {
		value = strings.ReplaceAll(value, "'", "''")
	}

	return fmt.Sprintf("'%s'", value)
}

func (g *SQLGenerator) isNumeric(value string) bool {
	if value == "" {
		return false
	}

	_, err := strconv.ParseInt(value, 10, 64)
	if err == nil {
		return true
	}

	_, err = strconv.ParseFloat(value, 64)
	return err == nil
}
