[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
activity_core = { path = "../core" }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
uuid.workspace = true
