#ifndef COMMON_H
#define COMMON_H

#include <pthread.h>
#include <stddef.h>

#define CHANNEL_NAME_MAX 64
#define USER_NAME_MAX 32
#define MESSAGE_CONTENT_MAX 512
#define MAX_CHANNELS 1024
#define MAX_USERS 1024
#define MAX_USER_CHANNELS 100

typedef enum {
    CHAT_OK = 0,
    CHAT_ERR_CHANNEL_EXISTS = -1,
    CHAT_ERR_CHANNEL_NOT_FOUND = -2,
    CHAT_ERR_CHANNEL_NOT_EMPTY = -3,
    CHAT_ERR_USER_NOT_FOUND = -4,
    CHAT_ERR_USER_ALREADY_SUBSCRIBED = -5,
    CHAT_ERR_USER_NOT_SUBSCRIBED = -6,
    CHAT_ERR_TOO_MANY_CHANNELS = -7,
    CHAT_ERR_TOO_MANY_USERS = -8,
    CHAT_ERR_TOO_MANY_SUBSCRIPTIONS = -9,
    CHAT_ERR_INVALID_ARG = -10,
    CHAT_ERR_MEMORY = -11,
    CHAT_ERR_CHANNEL_DESTROYED = -12
} ChatError;

#endif
