[package]
name = "budget_tracking_client"
version = "0.1.0"
edition = "2021"

[dependencies]
budget_tracking_core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
