server.port=8080
spring.application.name=work-shift-server

# Jackson configuration for java.time
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null
