package wiregen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

const genTemplate = `// Code generated by wire-di-gen. DO NOT EDIT.

package {{.PackageName}}

import (
{{- range .Imports}}
	{{.}}
{{- end}}
)

func Initialize({{range $i, $p := .ExternalParams}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) ({{if .HasError}}*{{.MainType}}, error{{else}}*{{.MainType}}{{end}}) {
{{- if .HasError}}
	_ = func() error { return nil }
{{- end}}
{{range $i, $stmt := .Statements}}
	{{$stmt}}
{{end}}
	return {{.MainVar}}{{if .HasError}}, nil{{end}}
}
`

type Generator struct {
	pkg  *PackageInfo
	graph *Graph
}

func NewGenerator(pkg *PackageInfo) *Generator {
	return &Generator{
		pkg: pkg,
	}
}

func (g *Generator) Generate() (string, error) {
	graph := NewGraph(g.pkg)
	if err := graph.Build(); err != nil {
		return "", err
	}
	g.graph = graph

	sorted, err := graph.TopologicalSort()
	if err != nil {
		return "", err
	}

	statements := make([]string, 0)
	varNameMap := make(map[string]string)
	var counter int
	hasError := false

	for _, node := range sorted {
		provider := node.Provider
		varName := g.generateVarName(provider.ReturnType, &counter)
		varNameMap[provider.ReturnType] = varName

		args := make([]string, 0)
		for _, param := range provider.Params {
			if prov, ok := g.findProviderForType(param.Type); ok {
				if existingVar, exists := varNameMap[prov.ReturnType]; exists {
					args = append(args, existingVar)
				} else {
					extVar := g.generateVarName(param.Type, &counter)
					varNameMap[param.Type] = extVar
					args = append(args, extVar)
				}
			} else {
				args = append(args, param.Name)
			}
		}

		callArgs := strings.Join(args, ", ")
		var stmt string
		if provider.ReturnsError {
			hasError = true
			stmt = fmt.Sprintf("%s, err := %s(%s)\n\tif err != nil {\n\t\treturn nil, err\n\t}", varName, provider.Name, callArgs)
		} else {
			stmt = fmt.Sprintf("%s := %s(%s)", varName, provider.Name, callArgs)
		}
		statements = append(statements, stmt)
	}

	externalParams := graph.GetExternalParams()
	mainType := ""
	mainVar := ""
	if len(sorted) > 0 {
		lastNode := sorted[len(sorted)-1]
		mainType = stripPointer(lastNode.Provider.ReturnType)
		mainVar = varNameMap[lastNode.Provider.ReturnType]
	}

	if mainVar == "" && len(externalParams) > 0 {
		mainVar = externalParams[0].Name
		mainType = stripPointer(externalParams[0].Type)
	}

	imports := g.collectImports(externalParams, sorted)

	data := struct {
		PackageName    string
		Imports        []string
		ExternalParams []*ExternalParam
		Statements     []string
		MainType       string
		MainVar        string
		HasError       bool
	}{
		PackageName:    g.pkg.Name,
		Imports:        imports,
		ExternalParams: externalParams,
		Statements:     statements,
		MainType:       mainType,
		MainVar:        mainVar,
		HasError:       hasError,
	}

	tmpl, err := template.New("wiregen").Parse(genTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

func (g *Generator) generateVarName(typeName string, counter *int) string {
	name := stripPointer(typeName)
	if name == "" {
		name = "var"
	}
	name = strings.ToLower(name[:1]) + name[1:]
	if *counter > 0 {
		name = fmt.Sprintf("%s%d", name, *counter)
	}
	*counter++
	return name
}

func (g *Generator) findProviderForType(typeName string) (*Provider, bool) {
	providers := g.pkg.GetProvidersByReturnType(typeName)
	if len(providers) == 0 {
		return nil, false
	}

	if len(providers) == 1 {
		return providers[0], true
	}

	for _, p := range providers {
		if p.IsExplicitProvider {
			return p, true
		}
	}

	return providers[0], true
}

func (g *Generator) collectImports(extParams []*ExternalParam, nodes []*GraphNode) []string {
	importSet := make(map[string]bool)

	for _, param := range extParams {
		if IsContextType(param.Type) {
			importSet["\"context\""] = true
		}
	}

	for _, node := range nodes {
		provider := node.Provider
		for _, param := range provider.Params {
			if IsContextType(param.Type) {
				importSet["\"context\""] = true
			}
			if strings.Contains(param.Type, ".") {
				parts := strings.SplitN(param.Type, ".", 2)
				if len(parts) == 2 {
					importSet[fmt.Sprintf("\"%s\"", parts[0])] = true
				}
			}
		}
		if strings.Contains(provider.ReturnType, ".") {
			parts := strings.SplitN(provider.ReturnType, ".", 2)
			if len(parts) == 2 {
				importSet[fmt.Sprintf("\"%s\"", parts[0])] = true
			}
		}
	}

	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}

	return imports
}
