server:
  port: 8105

spring:
  application:
    name: service-registry

logging:
  level:
    com.example.serviceregistry: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
