[package]
name = "forex_client"
version = "0.1.0"
edition = "2021"

[dependencies]
forex_core = { path = "../core" }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive", "env"] }
