[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
grading_core = { workspace = true }
axum = { workspace = true }
tracing-subscriber = "0.3"
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
