export const ErrorCodes = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  REFUND_PERIOD_EXPIRED: 'REFUND_PERIOD_EXPIRED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_REFUND_REQUEST: 'INVALID_REFUND_REQUEST',
  REFUND_ALREADY_EXISTS: 'REFUND_ALREADY_EXISTS',
  REFUND_NOT_FOUND: 'REFUND_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  LOGISTICS_NUMBER_REQUIRED: 'LOGISTICS_NUMBER_REQUIRED',
  WAREHOUSE_CONFIRM_REQUIRED: 'WAREHOUSE_CONFIRM_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  PARTIAL_REFUND_SHIPPING_NOT_REFUNDABLE: 'PARTIAL_REFUND_SHIPPING_NOT_REFUNDABLE',
  PRODUCT_ALREADY_CONSUMED: 'PRODUCT_ALREADY_CONSUMED',
  NOT_FOUND: 'NOT_FOUND'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

export interface ServiceError {
  code: ErrorCode;
  message: string;
}

export function createServiceError(code: ErrorCode, message: string): ServiceError {
  return { code, message };
}
