[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
booking_core = { path = "../core", package = "core" }
axum = "0.6"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
tower-http = { version = "0.4", features = ["cors"] }
clap = { version = "4.0", features = ["derive", "env"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
